-- Desativa a restrição de chave estrangeira temporariamente, se necessário
SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE TB_CUSTOMERS_GROUP_BILL RESTART IDENTITY;
TRUNCATE TABLE TB_GROUP_BILL_CUSTOMERS RESTART IDENTITY;
TRUNCATE TABLE TB_USERS RESTART IDENTITY;
TRUNCATE TABLE TB_CUSTOMERS RESTART IDENTITY;
TRUNCATE TABLE TB_GROUP_BILL RESTART IDENTITY;

-- Ativa a restrição de chave estrangeira novamente, se desativada
SET REFERENTIAL_INTEGRITY TRUE;